### ISSUE TITLE
Packaged v3 doesn't have `dist` folder

### ISSUE THREAD

**Issue by kaisermann** [Rich-Harris/estree-walker#33]
It seems that the packaged v3 version of the lib was deployed without the build artifacts 🙈 

https://npm-explorer.tk/?p=estree-walker

![CleanShot 2022-11-19 at 12 37 20](https://user-images.githubusercontent.com/12702016/202848809-eb75739e-f99d-4f28-a989-92bb137de62b.jpg)

**Comment by Conduitry** [comment]
It doesn't need any. It's directly consumed as unbundled ESM now. Is this causing a particular problem that you're seeing?

There's another issue on this repo about how this package can no longer be `require`d (which is because it has no CJS version in the published package), but this is also all intentional I believe.

**Comment by kaisermann** [comment]
I got the error from my test runner, but is probably for the same reason as the other issue you mentioned. I updated from v2 and saw no "dist" folder and didn't even think about looking at the package.json first 😅 

The error is a bit different from that issue though:
![CleanShot 2022-11-19 at 14 38 56](https://user-images.githubusercontent.com/12702016/202853467-b44ece4a-0928-468a-8d01-54061d1542e1.jpg)

Happened with `ts-jest` in a somewhat outdated environment. Will try to make it work and close this afterwards 🙏

**Comment by kaisermann** [comment]
Managed to make it work by updating jest and some other dependencies. Sorry for the unnecessary issue 🙌
